footer:
  links:
    - title: API
      url: https://go.validata.fr/api/v1/apidocs
    - title: Codes sources
      url: https://git.opendatafrance.net/validata
header:
  links:
    - title: Mode d'emploi
      url: https://opendatafrance.gitbook.io/validata/
    - title: Espace de discussion Validata
      url: https://riot.im/app/#/room/#validata:jailbreak.paris
    - title: API Validata
      url: https://api.validata.etalab.studio/apidocs
    - title: schema.data.gouv.fr
      url: https://schema.data.gouv.fr
    - title: Guide Schémas
      url: https://guides.etalab.gouv.fr/producteurs-schemas/#a-qui-s-adresse-ce-guide
    - title: Espace de discussion schémas
      url: https://github.com/etalab/schema.data.gouv.fr/issues
homepage:
  sections:
    - name: presentation
      title: Présentation
      description: Validata est une plateforme de validation de données ouvertes. Elle offre à ses utilisateurs la possibilité de vérifier la conformité de leurs données par rapport aux schémas de données nationaux de référence, répertoriés sur schema.data.gouv.fr. Depuis Mars 2022 l’association OpenDataFrance et Etalab mettent à disposition une version unique et commune de cette plateforme dans le cadre d’une coopération renforcée en matière de gouvernance et de stratégie sur les sujets liés à la standardisation des données ouvertes à l’échelle nationale. Cette plateforme commune résulte des travaux d’unification de leurs démarches et de leurs ressources respectives en matière de standardisation.
    - name: schema-datagouvfr
      title: schema.data.gouv.fr
      description: Les schémas référencés sur schema.data.gouv.fr.
      catalog: https://schema.data.gouv.fr/schemas/schemas.json
